### ISSUE TITLE
Publishing attitude and translational velocities 

### ISSUE THREAD

**Issue by di-math** [THI-Drone/fcc_bridge_package#5]
Hey,

just wanted to circle back here. I had in mind that the FCC-bridge logs the current attitude and translational velocities, as well as some other stuff, at the same rate it receives it from the FCC?

![image](https://github.com/THI-Drone/fcc_bridge_package/assets/60353189/30d7a099-beb8-436b-a68f-65e6db310377)

Just wanted to ask, if the logging can happen at a lower rate (0.25-1 Hz) to relief the /rosout topic and filtering efforts on the ground station?

**Comment by J0las** [comment]
Currently this is honestly not my most important concern. The safety functionality has just higher priority.
Maybe it is possible for your or @maf0115 to improve the filtering algorithm.
I´m already splitting up the different log types to sub loggers and even further sub sub loggers are planned.
That should then suffice to filter out only the interesting parts for the end user.

**Comment by J0las** [comment]
I created a quick and dirty package rosout_filter that at least for c++ shows how to filter by logger with an arbitrary regex.

**Comment by di-math** [comment]
Alright
