### ISSUE TITLE
No action when nodes crash during mission

### ISSUE THREAD

**Issue by incrazyboyy** [THI-Drone/fcc_bridge_package#6]
When I kill the mission_control_node or waypoint_node or qr_code_scanner_node, the fcc bridge doesn't notice that. Therefore, also no RTH gets triggered. The expected behaviour would be to monitor the heartbeat of these nodes and trigger RTH if one fails.

**Comment by Philipp66904** [comment]
Crafting truly groundbreaking safety features, like the one you discussed, requires a significant investment of time and resources. @J0las fully recognizes this, and we share that commitment.  As he develops this and other crucial safety improvements, we kindly ask for your patience. Your understanding is highly valued.

**Comment by Philipp66904** [comment]
implemented by @J0las a while ago
